theme: jekyll-theme-minimal
logo: https://raw.githubusercontent.com/visit-dav/visit-website/gh-pages/images/gallery-27.jpg
rawdata_baseurl: https://github.com/visit-dav/largedata/blob/master
collections:
  datarchives:
    output: true
    formats:
      - .tar.xz
      - .tar.gz
      - .zip
    format_remarks:
      - "lzma2 tar archive, ~2-3x < gzip."
      - "gzip tar archive (aka .tgz)."
      - "deflate zip archive."
  presentations:
    output: true
    formats:
      - .opt.pdf
      - .pdf
      - .pptx
    format_remarks:
      - "Minimum size PDF. Quality may suffer."
      - "Standard quality PDF. Not smallest possible."
      - "Native/orig. Maybe very large PowerPoint."
